export const AUTH_TOKEN = 'VIDISPINE-TOKEN';
export const AUTH_USERNAME = 'VIDISPINE-USERNAME';
export const AUTH_RUNAS = 'VIDISPINE-RUNAS';
export const AUTH_IS_AUTHENTICATED = 'VIDISPINE-IS-AUTHENTICATED';
export const AUTH_VIDISPINE_SERVER_URL = 'VIDISPINE-SERVER-URL';
export const PROXY_HEADER = 'X-Proxy-URL';
