name: Build With Public URL
on:
  workflow_dispatch:
    inputs:
      public_url:
        required: true
        description: The URL where the site will be published.

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Set artifact vars
        id: artifact-vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "encoded_url=$(node -p "encodeURIComponent('${{ github.event.inputs.public_url }}')")" >> $GITHUB_OUTPUT
      - name: Install dependencies
        run: npm ci
      - name: Build site
        run: PUBLIC_URL=${PUBLIC_URL} GENERATE_SOURCEMAP=false npm run build
        env:
          PUBLIC_URL: ${{ github.event.inputs.public_url }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: admin-tool_${{ steps.artifact-vars.outputs.sha_short }}_${{ steps.artifact-vars.outputs.encoded_url }}
          path: build
          retention-days: 1
