name: Build And Publish Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Configure npm
        run: npm config set script-shell bash
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
        shell: bash
      - name: Install app dependencies
        run: npm ci
        shell: bash
      - name: Build the Docker image
        run: PUBLIC_URL=/admin-tool npm run docker:buildx:push
        shell: bash

