name: Build And Publish Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Configure npm
        run: npm config set script-shell bash
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
        shell: bash
      - name: Install app dependencies
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install
        shell: bash
      - name: Build the Docker image
        run: PUBLIC_URL=/admin-tool npm run docker:buildx:push
        shell: bash

