name: Build And Publish Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Configure yarn
        run: yarn config set script-shell bash
      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
        shell: bash
      - name: Install app dependencies
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn install
        shell: bash
      - name: Build the Docker image
        run: yarn docker:build
        shell: bash
      - name: Push the Docker image
        run: yarn docker:push
        shell: bash

